### ISSUE TITLE
Exception while invoking method 'sendHTMLemail' TypeError: Handlebars.registerPartial is not a function

### ISSUE THREAD

**Issue by fligen** [simonhochrein/meteor-mjml#2]
> Exception while invoking method 'sendHTMLemail' TypeError: Handlebars.registerPartial is not a function
> I20160914-10:25:35.554(-5)?     at packages/simonhochrein:mjml/mjml.js:18:28
> I20160914-10:25:35.555(-5)?     at Array.forEach (native)
> I20160914-10:25:35.555(-5)?     at new MJML (packages/simonhochrein:mjml/mjml.js:13:15)
> I20160914-10:25:35.555(-5)?     at [object Object].sendHTMLemail (server/main.js:153:16)
> I20160914-10:25:35.555(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
> I20160914-10:25:35.556(-5)?     at packages/ddp-server/livedata_server.js:711:19
> I20160914-10:25:35.556(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
> I20160914-10:25:35.556(-5)?     at packages/ddp-server/livedata_server.js:709:40
> I20160914-10:25:35.556(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
> I20160914-10:25:35.556(-5)?     at packages/ddp-server/livedata_server.js:707:46
> I20160914-10:25:35.557(-5)?     at Session.method (packages/ddp-server/livedata_server.js:681:23)
> I20160914-10:25:35.557(-5)?     at packages/ddp-server/livedata_server.js:551:43

I keep getting this error in the terminal each time i try to send email. Any ideas?

**Comment by simonhochrein** [comment]
I have had the same problem
If you downgrade to meteor 1.3.4.2 from meteor 1.4 it will work
On Sep 14, 2016 10:29 AM, Fligen <notifications@github.com> wrote:
Exception while invoking method 'sendHTMLemail' TypeError: Handlebars.registerPartial is not a function
I20160914-10:25:35.554(-5)?     at packages/simonhochrein:mjml/mjml.js:18:28
I20160914-10:25:35.555(-5)?     at Array.forEach (native)
I20160914-10:25:35.555(-5)?     at new MJML (packages/simonhochrein:mjml/mjml.js:13:15)
I20160914-10:25:35.555(-5)?     at [object Object].sendHTMLemail (server/main.js:153:16)
I20160914-10:25:35.555(-5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
I20160914-10:25:35.556(-5)?     at packages/ddp-server/livedata_server.js:711:19
I20160914-10:25:35.556(-5)?     at [object Object]..extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160914-10:25:35.556(-5)?     at packages/ddp-server/livedata_server.js:709:40
I20160914-10:25:35.556(-5)?     at [object Object]..extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160914-10:25:35.556(-5)?     at packages/ddp-server/livedata_server.js:707:46
I20160914-10:25:35.557(-5)?     at Session.method (packages/ddp-server/livedata_server.js:681:23)
I20160914-10:25:35.557(-5)?     at packages/ddp-server/livedata_server.js:551:43


I keep getting this error in the terminal each time i try to send email. Any ideas?

**Comment by fligen** [comment]
This is not working for me.

**Comment by simonhochrein** [comment]
That's very strange

**Comment by mkorban** [comment]
I have the same problem
Meteor 1.6.0.1

**Comment by simonhochrein** [comment]
This issue is resolved with the latest release of the package.
